#curl -X GET "http://localhost:3022/activate?username=s.amwisetwofoot1525@gmail.com&password=QAWSED!@#"
#curl -X GET "http://localhost:3022/activate?username=sa.mwisetwofoot1525@gmail.com&password=QAWSED!@#"
#curl -X GET "http://localhost:3022/activate?username=sam.wisetwofoot1525@gmail.com&password=QAWSED!@#"
curl -X GET "http://localhost:3022/activate?username=GooDeeBotOne&password=QAWSED!@#"
curl -X GET "http://localhost:3022/activate?username=GooDeeBotTwo&password=QAWSED!@#"
curl -X GET "http://localhost:3022/activate?username=GooDeeBotThree&password=QAWSED!@#"