#curl -X GET "http://localhost:3022/activate?username=s.amwisetwofoot1525@gmail.com&password=QAWSED!@#"
#curl -X GET "http://localhost:3022/activate?username=sa.mwisetwofoot1525@gmail.com&password=QAWSED!@#"
#curl -X GET "http://localhost:3022/activate?username=sam.wisetwofoot1525@gmail.com&password=QAWSED!@#"
curl -X GET "http://localhost:3022/activate?username=goodeefi&password=QAWSED!@#"
curl -X GET "http://localhost:3022/activate?username=GooDeeBotMint&password=QAWSED!@#"
curl -X GET "http://localhost:3022/activate?username=GooDeeBotNew&password=QAWSED!@#"
curl -X GET "http://localhost:3022/activate?username=GooDeeBotOS&password=QAWSED!@#"